SELECT 
station_national_code
, objectid
, stationid
, stationid
, stationname
, stationtype
, wfdwisecode
, entitycode
, entityname
, wbwfdwisecode
, monitoredentitytype
, localauthority
, riverbasindistrict
, createdbyorganisation
, epastationtype
, segcd
, media
, datasource
, biological
, chemical
, wfd
, gwquality
, gwquantity
, epalink
, easting
, northing
, lastupdatedate
, lastupdatecomment
, measurealong
, associatedfeature
, associatedfeaturename
, localauthorityspatial
, latitude
, longitude
, location
FROM vector.mon_waterstations
