SELECT 
LicenceView.[createdby] AS [createdbyLicenceView],
LicenceView.[createdbyname] AS [createdbynameLicenceView],
LicenceView.[createdbyyominame] AS [createdbyyominameLicenceView],
LicenceView.[createdon] AS [createdonLicenceView],
LicenceView.[createdonutc] AS [createdonutcLicenceView],
LicenceView.[createdonbehalfby] AS [createdonbehalfbyLicenceView],
LicenceView.[createdonbehalfbyname] AS [createdonbehalfbynameLicenceView],
LicenceView.[createdonbehalfbyyominame] AS [createdonbehalfbyyominameLicenceView],
LicenceView.[epa_additionalapplicationfee],
LicenceView.[epa_additionalapplicationfee_base],
LicenceView.[epa_additionalfeedate],
LicenceView.[epa_additionalfeedateutc],
LicenceView.[epa_adminofficer],
LicenceView.[epa_adminofficername],
LicenceView.[epa_adminofficeryominame],
LicenceView.[epa_agglomerationpe],
LicenceView.[epa_agglomerationtype],
LicenceView.[epa_agglomerationtypename],
LicenceView.[epa_application6steps],
LicenceView.[epa_application6stepsname],
LicenceView.[epa_applicationfee],
LicenceView.[epa_applicationfee_base],
LicenceView.[epa_boardmeetingdate],
LicenceView.[epa_boardmeetingdateutc],
LicenceView.[epa_dateoflicence],
LicenceView.[epa_dateoflicenceutc],
LicenceView.[epa_dateoflicenceapplication],
LicenceView.[epa_dateoflicenceapplicationutc],
LicenceView.[epa_division],
LicenceView.[epa_divisionname],
LicenceView.[epa_earliestfddate],
LicenceView.[epa_earliestfddateutc],
LicenceView.[epa_eisreceived],
LicenceView.[epa_eisreceivedname],
LicenceView.[epa_eisrequired],
LicenceView.[epa_eisrequiredname],
LicenceView.[epa_fdcirculatedtoboard],
LicenceView.[epa_fdcirculatedtoboardutc],
LicenceView.[epa_inspector],
LicenceView.[epa_inspectorname],
LicenceView.[epa_inspectoryominame],
LicenceView.[epa_latestfddate],
LicenceView.[epa_latestfddateutc],
LicenceView.[epa_legacyrefundnotifieddate],
LicenceView.[epa_legacyrefundnotifieddateutc],
LicenceView.[epa_legacyrefundpercent],
LicenceView.[epa_legacyrefundrecommenddate],
LicenceView.[epa_legacyrefundrecommenddateutc],
LicenceView.[epa_licenceapplicationstatus],
LicenceView.[epa_licenceapplicationstatusname],
LicenceView.[epa_licenceid],
LicenceView.[epa_licencestatus],
LicenceView.[epa_licencestatusname],
LicenceView.[epa_licencetype],
LicenceView.[epa_licencetypename],
LicenceView.[epa_name],
LicenceView.[epa_oclradmin],
LicenceView.[epa_oclradmincopy],
LicenceView.[epa_oclradmincopyname],
LicenceView.[epa_oclradmincopyyominame],
LicenceView.[epa_oclradminname],
LicenceView.[epa_oclradminyominame],
LicenceView.[epa_oclrinspector],
LicenceView.[epa_oclrinspectorcopy],
LicenceView.[epa_oclrinspectorcopyname],
LicenceView.[epa_oclrinspectorcopyyominame],
LicenceView.[epa_oclrinspectorname],
LicenceView.[epa_oclrinspectoryominame],
LicenceView.[epa_oeaauditor],
LicenceView.[epa_oeaauditorname],
LicenceView.[epa_oeaauditoryominame],
NULL AS [epa_oealaboratory],
NULL AS [epa_oealaboratoryname],
NULL AS [epa_oeeinspector],
NULL AS [epa_oeeinspectorname],
NULL AS [epa_oeeinspectoryominame],
NULL AS [epa_oeeregionalteam],
NULL AS [epa_oeeregionalteamname],
NULL AS [epa_oeeregionalteamyominame],
LicenceView.[epa_refundamount],
LicenceView.[epa_refundamount_base],
LicenceView.[epa_reg12duedate],
LicenceView.[epa_reg12duedateutc],
LicenceView.[epa_reg18duedate],
LicenceView.[epa_reg18duedateutc],
LicenceView.[epa_reg20duedate],
LicenceView.[epa_reg20duedateutc],
LicenceView.[epa_reg25ciiduedate],
LicenceView.[epa_reg25ciiduedateutc],
LicenceView.[epa_reg303duedate],
LicenceView.[epa_reg303duedateutc],
LicenceView.[epa_regno],
LicenceView.[epa_rlcirculatedtoboard],
LicenceView.[epa_rlcirculatedtoboardutc],
LicenceView.[epa_sfadco],
LicenceView.[epa_sfadconame],
LicenceView.[epa_siteid],
LicenceView.[epa_siteidname],
LicenceView.[epa_waterservicesauthority],
LicenceView.[epa_waterservicesauthorityname],
LicenceView.[epa_waterservicesauthorityyominame],
LicenceView.[exchangerate],
LicenceView.[importsequencenumber],
LicenceView.[lema_amountearned],
LicenceView.[lema_amountearned_base],
LicenceView.[lema_amountoutstanding],
LicenceView.[lema_amountoutstanding_base],
LicenceView.[lema_apprcvddate],
LicenceView.[lema_apprcvddateutc],
LicenceView.[lema_ceaseddate],
LicenceView.[lema_ceaseddateutc],
LicenceView.[lema_compliancefailuredate],
LicenceView.[lema_compliancefailuredateutc],
LicenceView.[lema_designbuildoperatecontract],
LicenceView.[lema_designbuildoperatecontractname],
NULL AS [lema_enforcementriskcategory],
NULL AS [lema_enforcementriskcategoryname],
LicenceView.[lema_inclusioninlocalprogrammesofworks],
LicenceView.[lema_inclusioninlocalprogrammesofworksname],
NULL AS [lema_inspectorsupdate],
LicenceView.[lema_isthereacoapplicant],
LicenceView.[lema_isthereacoapplicantname],
LicenceView.[lema_latestdecisiondate],
LicenceView.[lema_latestdecisiondateutc],
LicenceView.[lema_licenceexpirydate],
LicenceView.[lema_licenceexpirydateutc],
LicenceView.[lema_licencestartdate],
LicenceView.[lema_licencestartdateutc],
null,
null,
LicenceView.[lema_prioritystatus],
LicenceView.[lema_prioritystatusname],
LicenceView.[lema_proposedcompletiondateofworks],
LicenceView.[lema_proposedcompletiondateofworksutc],
LicenceView.[lema_proposedworkscompdate],
LicenceView.[lema_proposedworkscompdateutc],
LicenceView.[lema_publicprivatepartnership],
LicenceView.[lema_publicprivatepartnershipname],
LicenceView.[lema_refundrequestdecision],
LicenceView.[lema_refundrequestdecisionutc],
LicenceView.[lema_refundrequested],
LicenceView.[lema_refundrequestedname],
LicenceView.[lema_refundrequestreceived],
LicenceView.[lema_refundrequestreceivedutc],
LicenceView.[lema_refuseddate],
LicenceView.[lema_refuseddateutc],
LicenceView.[lema_reg182ackdate],
LicenceView.[lema_reg182ackdateutc],
LicenceView.[lema_reg184bnoticedate],
LicenceView.[lema_reg184bnoticedateutc],
LicenceView.[lema_reg202bnoticedate],
LicenceView.[lema_reg202bnoticedateutc],
LicenceView.[lema_reg202cnoticedate],
LicenceView.[lema_reg202cnoticedateutc],
LicenceView.[lema_reg205ackdate],
LicenceView.[lema_reg205ackdateutc],
LicenceView.[lema_reg231replyduedate],
LicenceView.[lema_reg231replyduedateutc],
LicenceView.[lema_reg25c1ackdate],
LicenceView.[lema_reg25c1ackdateutc],
LicenceView.[lema_reg25c2replyduedate],
LicenceView.[lema_reg25c2replyduedateutc],
LicenceView.[lema_reg283replyduedate],
LicenceView.[lema_reg283replyduedateutc],
LicenceView.[lema_reviewreceiveddate],
LicenceView.[lema_reviewreceiveddateutc],
LicenceView.[lema_revokeddate],
LicenceView.[lema_revokeddateutc],
LicenceView.[lema_sector],
LicenceView.[lema_sectorname],
LicenceView.[lema_startfdduephasedate],
LicenceView.[lema_startfdduephasedateutc],
LicenceView.[lema_submissioncount],
LicenceView.[lema_substatus],
LicenceView.[lema_substatusname],
LicenceView.[lema_surrendereddate],
LicenceView.[lema_surrendereddateutc],
LicenceView.[lema_withdrawndate],
LicenceView.[lema_withdrawndateutc],
LicenceView.[lema_wsipcommencedate],
LicenceView.[lema_wsipcommencedateutc],
LicenceView.[lema_wsipcommencementdate],
LicenceView.[lema_wsipcommencementdateutc],
LicenceView.[lema_wsipcommitmentreceived],
LicenceView.[lema_wsipcommitmentreceivedname],
LicenceView.[lema_wsipstatus],
LicenceView.[lema_wsipstatusname],
LicenceView.[modifiedby] AS [modifiedbyLicenceView],
LicenceView.[modifiedbyname] AS [modifiedbynameLicenceView],
LicenceView.[modifiedbyyominame] AS [modifiedbyyominameLicenceView],
LicenceView.[modifiedon] AS [modifiedonlicenceview],
LicenceView.[modifiedonutc] AS [modifiedonutclicenceview],
LicenceView.[modifiedonbehalfby] AS [modifiedonbehalfbyLicenceView],
LicenceView.[modifiedonbehalfbyname] AS [modifiedonbehalfbynameLicenceView],
LicenceView.[modifiedonbehalfbyyominame] AS [modifiedonbehalfbyyominameLicenceView],
LicenceView.[overriddencreatedon] AS [overriddencreatedonLicenceView],
LicenceView.[overriddencreatedonutc] AS [overriddencreatedonutcLicenceView],
LicenceView.[ownerid],
LicenceView.[owneriddsc],
LicenceView.[owneridname],
LicenceView.[owneridtype],
LicenceView.[owneridyominame],
LicenceView.[owningbusinessunit],
LicenceView.[owningteam],
LicenceView.[owninguser],
LicenceView.[statecode],
LicenceView.[statecodename],
LicenceView.[statuscode],
LicenceView.[statuscodename],
LicenceView.[timezoneruleversionnumber],
LicenceView.[transactioncurrencyid],
LicenceView.[transactioncurrencyidname],
LicenceView.[utcconversiontimezonecode],
LicenceView.[crm_moneyformatstring],
LicenceView.[crm_priceformatstring],
SiteView.[createdby] AS [createdbySiteView],
SiteView.[createdbyname] AS [createdbynameSiteView],
SiteView.[createdbyyominame] AS [createdbyyominameSiteView],
SiteView.[createdon] AS [createdonSiteView],
SiteView.[createdonutc] AS [createdonutcSiteView],
SiteView.[createdonbehalfby] AS [createdonbehalfbySiteView],
SiteView.[createdonbehalfbyname] AS [createdonbehalfbynameSiteView],
SiteView.[createdonbehalfbyyominame] AS [createdonbehalfbyyominameSiteView],
SiteView.[emailaddress] AS [emailaddressSiteView],
SiteView.[epa_accountid],
SiteView.[epa_accountidname],
SiteView.[epa_accountidyominame],
SiteView.[epa_accountsiteid],
SiteView.[epa_accountsiteidname],
SiteView.[epa_accountsiteidyominame],
SiteView.[epa_address1],
SiteView.[epa_address2],
SiteView.[epa_address3],
SiteView.[epa_address4],
SiteView.[epa_address_county],
NULL AS epa_aggid,
SiteView.[epa_agglomeration],
SiteView.[epa_agglomerationpe],
SiteView.[epa_county],
SiteView.[epa_countyname],
SiteView.[epa_eastings],
SiteView.[epa_esbsubstations],
SiteView.[epa_esbsubstationsname],
SiteView.[epa_healthboard],
SiteView.[epa_healthboardname],
SiteView.[epa_healthboardyominame],
SiteView.[epa_leveloftreatment],
SiteView.[epa_leveloftreatmentname],
SiteView.[epa_licenseno],
SiteView.[epa_localauthority],
SiteView.[epa_localauthorityname],
SiteView.[epa_localauthorityyominame],
SiteView.[epa_nacecode],
SiteView.[epa_nacecodename],
SiteView.[epa_name],
SiteView.[epa_northings],
NULL AS [epa_nutrientreduction],
NULL AS [epa_nutrientreductionname],
NULL AS [epa_nutrientreductiontype],
NULL AS [epa_nutrientreductiontypename],
SiteView.[epa_oeeinspectorid],
SiteView.[epa_oeeinspectoridname],
SiteView.[epa_oeeinspectoridyominame],
SiteView.[epa_othertreatmenttype],
SiteView.[epa_pcbcode],
SiteView.[epa_pcborgcode],
SiteView.[epa_pcbstatus],
SiteView.[epa_pcbstatusname],
SiteView.[epa_pemeasured],
SiteView.[epa_pemeasuredname],
SiteView.[epa_phonenumber],
SiteView.[epa_plantdesignpe],
SiteView.[epa_planttype],
SiteView.[epa_planttypename],
SiteView.[epa_postcode],
SiteView.[epa_sensitivearea],
SiteView.[epa_sensitiveareaname],
SiteView.[epa_sitecode],
SiteView.[epa_siteid],
SiteView.[epa_sitemanned],
SiteView.[epa_sitemannedname],
SiteView.[epa_towncity],
SiteView.[epa_treatmentplantname],
SiteView.[epa_typeoftreatment],
SiteView.[epa_typeoftreatmentname],
NULL AS [epa_uvtreatmentinplace],
NULL AS [epa_uvtreatmentinplacename],
SiteView.[epa_yearofconstruction],
SiteView.[importsequencenumber],
SiteView.[lema_actualpe],
SiteView.[lema_address1_correspondence],
SiteView.[lema_address2_correspondence],
SiteView.[lema_address3_correspondence],
SiteView.[lema_address4_correspondence],
SiteView.[lema_agglomerationtype],
SiteView.[lema_agglomerationtypename],
SiteView.[lema_county_correspondence],
SiteView.[lema_county_correspondencename],
SiteView.[lema_townland],
SiteView.[modifiedby] AS [modifiedbySiteView],
SiteView.[modifiedbyname] AS [modifiedbynameSiteView],
SiteView.[modifiedbyyominame] AS [modifiedbyyominameSiteView],
SiteView.[modifiedon] AS [modifiedonSiteView],
SiteView.[modifiedonutc] AS [modifiedonutcSiteView],
SiteView.[modifiedonbehalfby] AS [modifiedonbehalfbySiteView],
SiteView.[modifiedonbehalfbyname] AS [modifiedonbehalfbynameSiteView],
SiteView.[modifiedonbehalfbyyominame] AS [modifiedonbehalfbyyominameSiteView],
SiteView.[overriddencreatedon] AS [overriddencreatedonSiteView],
SiteView.[overriddencreatedonutc] AS [overriddencreatedonutcSiteView],
SiteView.[organizationid],
SiteView.[organizationidname],
SiteView.[statecode],
SiteView.[statecodename],
SiteView.[statuscode],
SiteView.[statuscodename],
SiteView.[timezoneruleversionnumber],
SiteView.[utcconversiontimezonecode]
FROM 	[Filteredepa_licence] 		AS LicenceView
JOIN 	Filteredepa_site 			AS SiteView 	ON LicenceView.epa_siteid = SiteView.epa_siteid
WHERE 	LicenceView.[epa_licencetype] IN (919780000, 919780001, 919780002, 919780003,953210004, 953210001, 953210002)
AND 	LicenceView.[epa_regno] 	IS NOT NULL
AND 	LicenceView.[epa_regno] 	NOT LIKE '[a-z]%99%[0-9][0-9]-[0-9][0-9]'
--AND		LicenceView.[modifiedon] >= :sql_last_value