SELECT DISTINCT SiteView.[createdby],
SiteView.[createdbyname],
SiteView.[createdbyyominame],
SiteView.[createdon],
SiteView.[createdonutc],
SiteView.[createdonbehalfby],
SiteView.[createdonbehalfbyname],
SiteView.[createdonbehalfbyyominame],
SiteView.[emailaddress],
SiteView.[epa_accountid],
SiteView.[epa_accountidname],
SiteView.[epa_accountidyominame],
SiteView.[epa_accountsiteid],
SiteView.[epa_accountsiteidname],
SiteView.[epa_accountsiteidyominame],
SiteView.[epa_address1],
SiteView.[epa_address2],
SiteView.[epa_address3],
SiteView.[epa_address4],
SiteView.[epa_address_county],
NULL AS epa_aggid,
SiteView.[epa_agglomeration],
SiteView.[epa_agglomerationpe],
SiteView.[epa_county],
SiteView.[epa_countyname],
SiteView.[epa_eastings],
SiteView.[epa_esbsubstations],
SiteView.[epa_esbsubstationsname],
SiteView.[epa_healthboard],
SiteView.[epa_healthboardname],
SiteView.[epa_healthboardyominame],
SiteView.[epa_leveloftreatment],
SiteView.[epa_leveloftreatmentname],
SiteView.[epa_licenseno],
SiteView.[epa_localauthority],
SiteView.[epa_localauthorityname],
SiteView.[epa_localauthorityyominame],
SiteView.[epa_nacecode],
SiteView.[epa_nacecodename],
SiteView.[epa_name],
SiteView.[epa_northings],
NULL AS [epa_nutrientreduction],
NULL AS [epa_nutrientreductionname],
NULL AS [epa_nutrientreductiontype],
NULL AS [epa_nutrientreductiontypename],
SiteView.[epa_oeeinspectorid],
SiteView.[epa_oeeinspectoridname],
SiteView.[epa_oeeinspectoridyominame],
SiteView.[epa_othertreatmenttype],
SiteView.[epa_pcbcode],
SiteView.[epa_pcborgcode],
SiteView.[epa_pcbstatus],
SiteView.[epa_pcbstatusname],
SiteView.[epa_pemeasured],
SiteView.[epa_pemeasuredname],
SiteView.[epa_phonenumber],
SiteView.[epa_plantdesignpe],
SiteView.[epa_planttype],
SiteView.[epa_planttypename],
SiteView.[epa_postcode],
SiteView.[epa_sensitivearea],
SiteView.[epa_sensitiveareaname],
SiteView.[epa_sitecode],
SiteView.[epa_siteid],
SiteView.[epa_sitemanned],
SiteView.[epa_sitemannedname],
SiteView.[epa_towncity],
SiteView.[epa_treatmentplantname],
SiteView.[epa_typeoftreatment],
SiteView.[epa_typeoftreatmentname],
NULL AS [epa_uvtreatmentinplace],
NULL AS [epa_uvtreatmentinplacename],
SiteView.[epa_yearofconstruction],
SiteView.[importsequencenumber],
SiteView.[lema_actualpe],
SiteView.[lema_address1_correspondence],
SiteView.[lema_address2_correspondence],
SiteView.[lema_address3_correspondence],
SiteView.[lema_address4_correspondence],
SiteView.[lema_agglomerationtype],
SiteView.[lema_agglomerationtypename],
SiteView.[lema_county_correspondence],
SiteView.[lema_county_correspondencename],
SiteView.[lema_townland],
SiteView.[modifiedby],
SiteView.[modifiedbyname],
SiteView.[modifiedbyyominame],
SiteView.[modifiedon],
SiteView.[modifiedonutc],
SiteView.[modifiedonbehalfby],
SiteView.[modifiedonbehalfbyname],
SiteView.[modifiedonbehalfbyyominame],
SiteView.[organizationid],
SiteView.[organizationidname],
SiteView.[overriddencreatedon],
SiteView.[overriddencreatedonutc],
SiteView.[statecode],
SiteView.[statecodename],
SiteView.[statuscode],
SiteView.[statuscodename],
SiteView.[timezoneruleversionnumber],
SiteView.[utcconversiontimezonecode]
FROM  Filteredepa_site AS SiteView
JOIN  Filteredepa_licence AS LicenceView ON SiteView.epa_siteid = LicenceView.epa_siteid
WHERE LicenceView.[epa_licencetype] IN (919780000, 919780001, 919780002, 919780003,953210004, 953210001, 953210002)
--AND	  SiteView.[modifiedonutc] >= :sql_last_value --OTHEROTHEROTHER TEXT
